# Copied from https://coderefinery.github.io/documentation/gh_workflow/ and
# modified to use the GitHub Actions sphinx-build action
name: docs
on: [pull_request]
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the whole repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          branch: main
          owner: cadwrdeltamodeling
          repository: suxarray
          path: ./suxarray
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Sphinx build
        run: |
          pip install .
          pip install sphinx sphinx_rtd_theme myst-nb sphinx-versioned-docs
          sphinx-apidoc -o docs suxarray
          sphinx-versioned --output docs/_build --local-conf docs/conf.py --branch "main" --main-branch "main"
        working-directory: ./suxarray
